config:
    clickToSeeMine: '$2Click to see mine configuration!'
    clickToRemove: '$4Click to remove!'
    clickToEdit: '$2Click to edit!'
    clickToLoad: '$2Click to load this file!'
    noMisformattedFiles: '$2No misformated files!'
    foundFiles: '$1Found a total of $2%total% $1not loaded mines'
globalItems:
#DO NOT DELETE ANY OF THESE!!!
#You can edit them AS LONG AS YOU DON'T DELETE THEM
    splitter:
        type: IRON_FENCE
        data: 0
        name: '&r'
    teleporter:
        type: ENDER_PEARL
        data: 0
        name: '$2Teleport to mine location!'
        lore:
            - '$1The spawn location will be'
            - '$1the top-y-center of the mine :)'
    clearMaterials:
        type: BARRIER
        data: 0
        name: '$2Remove all the materials!'
        lore:
            - '$1Remember that by removing all'
            - '$1the materials, the mine reset'
            - '$1will kinda be ignored until you add'
            - '$1some materials to the composition :P'
    removeMaterial:
        type: BARRIER
        data: 0
        name: '$4Click to remove'
        lore:
            - '$1Removes the material'
            - '$1from the composition'
    resetNow:
        type: WOOD_PICKAXE
        data: 0
        name: '$2Reset mine'
        lore:
            - '$1Forces the mine to reset'
            - '$1like... $4RIGHT NOW!'
    toogleMaterialEditor:
        type: SLIME_BALL
        data: 0
        name: '$2Toogle Materials/Effects'
        lore:
            - '$1Toogles between editing'
            - '$1materials and effects.'
    noMine:
        type: STAINED_GLASS_PANE
        data: 15
        name: '$4No mine found'
        lore:
            - '$1There are no mines'
            - '$1to display here'
    unloadedMines:
        type: STAINED_GLASS_PANE
        data: 15
        name: '$4No file found'
        lore:
            - '$1Disabled mine files'
            - '$1will appear here!'
            - '$1Once they appear, click'
            - '$1them to load the mine!'
    fillMine:
        type: CHEST
        data: 0
        name: '$2Fill mine'
        lore:
            - '$1Drop a block here'
            - '$1and we''ll fill the'
            - '$1mine with it!'
    couldNotLoadFiles:
        type: BOOK
        data: 0
        name: '$2Misconfigured Files'
        lore:
            - '$3The followings files could not be read.'
    iconNotLoaded:
        type: BARRIER
        data: 0
        name: '$2%name%'
        lore:
            - '$3The icon for this mine is not loaded yet!'
            - '$3But fear not my dear server owner!'
            - '$3This will be replaced with the mine icon'
            - '$3once it''s loaded :)'
    refresh:
        type: DIAMOND
        data: 0
        name: '$2Refresh menu'
        lore:
            - '$3Refreshes this menu!'
    deleteMine:
        type: TNT
        data: 0
        name: '$2Delete mine'
        lore: 
            - '$1Deletes this mine, file included.'
            - '$1You won''t be able to load it again.'
            - '$1If you want to simply unload this'
            - '$1mine, check $2Disable mine'
    disableMine:
        type: REDSTONE
        data: 0
        name: '$2Disable mine'
        lore: 
            - '$1Disables/Unloads this mine.'
            - '$1You can enable it again on it''s'
            - '$1config file or through the Main Menu'
    clearMine:
        type: REDSTONE_BLOCK
        data: 0
        name: '$2Clear mine'
        lore: 
            - '$1Remove''s all the blocks of'
            - '$1the mine, useful for events.'
    back:
        type: EMERALD
        data: 0
        name: '&a&lGo back'
    emptyMaterial:
        type: STAINED_GLASS_PANE
        data: 15
        name: '$4No material'
        lore: 
            -'$1Drop a material here to add!'
    empty:
        type: STAINED_GLASS_PANE
        data: 15
        name: '&r'
    emptyEffect:
        type: STAINED_GLASS_PANE
        data: 15
        name: '$4No effect'
        lore: 
            -'$1Drop a potion here to add it''s effects!'
            -'$1Right click to remove the potion!'
    info:
        type: BOOK
        data: 0
        name: '$2Stats'
        lore:
            - '$3Total percentage: $1%totalpercentage%'
            - '$3Total materials: $1%totalmaterials%'
    balanceMaterials:
        type: IRON_INGOT
        data: 0
        name: '$2Balance materials'
        lore:
            - '$1Divides the percentage'
            - '$1through all the materials'
    resetMaterials:
        type: GOLD_INGOT
        data: 0
        name: '$2Reset materials'
        lore:
            - '$1Sets all the materials'
            - '$1to 5% percent. useful if'
            - '$1you want to set percentages'
            - '$1again without removing materials'
mainMenu:
    name: "$2&lMegui"
    #The total lanes the main menu will have
    totalLanes: 6
    icons:
        #DON'T DELETE THIS
        main:
            type: GOLD_PICKAXE
            data: 0
            name: '$2&lMine Editor (MEGUI)'
            lore:
            - '$3An editor provided by' 
            - '%prefix% $3to easily edit mines! :)'
