#Very complex config v96.0

#Everything below here will affect ~ALL~ the mines
global:
  
  #Forces all the mines to use the default broadcast message in messages.yml
  forceDefaultBroadcastMessage: true
  
  #Uses HolographicDisplays to displays Hologram information about mines!
  #You can configurate holograms individualy on their respective files, or you can force
  #them to use the default hologram pattern, which is right below.
  #This will only work if you have Holographic Displays installed on your server!
  useHolographicDisplays: false
  
  #Forces mine to use the hologram config below
  forceDefaultHologramOnAllMines: false
  
  #This is the preset that will be setup to all the mines
  #if forceHologramOnAllMines is enabled
  defaultHologramDisplay:
   - '%alias%'
   - '&eBanana'
   - '&6Potato'
   - '&eBanana'