globalItens:
    splitter:
        type: IRON_FENCE
        data: 0
        name: '&r'
mainMenu:
    name: "&a&lMine Editor"
    #The total lanes the main menu will have
    totalLanes: 7
    icons:
        main:
            type: DIAMOND_PICKAXE
            data: 0
            name: '&a&lMine editor'
            lore:
            - ''
            - ''
mineMenu:
    #Must be divisible by 9
    totalLanes: 5
